root_path: "/gpfs/bbp.cscs.ch/project/proj96/home/ecker/simulations/011a9b05-2d6a-49b0-8ed9-e735df2460a8"

input_patterns_fname: "input_spikes/stimulus_stream__start2000__end121501__rate2__seed9.txt"
pattern_gids_fname: "input_spikes/Thalamocortical_input_VPM__hex_O1__supersample__nc100__pct12__seed9__pattern_gids.pkl"

h5_out:
    file_name: "assemblies.h5"
    prefixes:
        spikes: "spikes"
        average_spikes: "average_spikes"
        assemblies: "assemblies"
        consensus_assemblies: "consensus"
        average_assemblies: "average_assemblies"
        connectivity: "connectivity"
        single_cell_features: "single_cell"

root_fig_path: "/gpfs/bbp.cscs.ch/project/proj96/home/ecker/figures/v7_assemblies"

preprocessing_protocol:
    target: "hex_O1Excitatory"
    t_start: 1500
    t_end: 122000
    bin_size: 20
    threshold_rate: True
    surr_rate_method: "keep_sc_rate"
